[package]
name = "sui_identities"
version = "0.0.1"

[dependencies]
Sui = { local = "../../sui/crates/sui-framework/"}

[addresses]
identities =  "0x0"
sui =  "0000000000000000000000000000000000000002"
